env:
  name: CartPole-v1
  init:
    id: CartPole-v1
    render_mode: rgb_array
  reset: {}
  wrappers: []
agent:
  name: DQN
  init:
    target_update_interval: 1000
    learning_rate: 1.0e-3
    gamma: 0.99
    decay: 0.01
    scheduler_last_ratio: 0.0,
    scheduler_iters: 200000
  reset: {}
buffer:
  name: Buffer
  init:
    maxlen:
  reset: {}
runner:
  name: Runner
  init: {}
  reset: {}
  run:
    total_timesteps: 200000
    learning_starts: 0
    trainfreq: 1
  evaluate:
    savedir: results/CartPole-v1/DQN
    moviefreq: 1
