env:
  name: CartPoleEnv
  init:
    t_max: 15.0
    dt: 0.02
    m_cart: 1.0
    m_ball: 1.0
    l_pole: 1.0
  reset:
    initial_t: 0.0
    initial_x:
      - 0.0
      - 0.0
      - 1.0
      - 1.8707963267948966
      - 0.0
      - 0.0
      - 0.0
      - 0.0
    target_x:
      - 1.0
      - 0.0
      - 1.0
      - 1.5707963267948966
      - 0.0
      - 0.0
      - 0.0
      - 0.0
    Q: 0.01
    Qf:
      - 10.0
      - 5.0
      - 5.0
      - 5.0
    R: 0.01
    w_base: 1.0
    w_final: 5.0
  wrappers:
    - name: DQNMultiBody
      init:
        state_low:
          - -3.5
          - -0.8
          - -5.0
          - -5.0
        state_high:
          - 3.5
          - 0.8
          - 5.0
          - 5.0
        action_low:
          - -25.0
        action_high:
          - 25.0
        t_interval: 0.1
        n_action_splits: 20
    - name: RLTimeObservation
      init: {}
agent:
  name: DQN
  init:
    eps_low: 0.01
    initial_eps: 1.0
    decay: 0.01
    learning_rate: 1.0e-3
    gamma: 0.999
    batch_size: 256
    eps_update_freq: 10
    tau: 1.0
    target_update_interval: 1000
    max_grad_norm: 10.0
    scheduler_last_ratio: 1.0
    scheduler_iters: 0
    loaddir:
  reset: {}
buffer:
  name: Buffer
  init:
    maxlen: 500000
  reset: {}
runner:
  name: Runner
  init: {}
  reset: {}
  run:
    total_timesteps: 40000
    learning_starts: 1000
    trainfreq: 1
  evaluate:
    moviefreq: 1
    renderfreq: 1
  save:
    savedir: results/CartPoleEnv/Balance/DQN/scratch/Q_0.01_R_0.01_Qf_10.0_5.0_5.0_5.0
